Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/hirsute64"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    config.vm.synced_folder "qemu", "/"
    config.vm.provision "shell", path: "vagrant_setup.sh"
 end
